### ISSUE TITLE
请问在本地怎么运行这个项目

### ISSUE THREAD

**Issue by ugod3** [LiuXIn011/rightHouse#4]
搭载在windows，按最低配置，我得到两个uni-app api，在D:\rightHouse-develop\RH-server\config\config.default.js中配置好需要的服务，oss，Nginx，redis都在cmd中运行了，然后用Hbuilder中浏览器打开这几个客户端，但是卡在微信登录上，您看得到我目前的进度吗

**Comment by LiuXIn011** [comment]
微信登录需要有企业认证的小程序appid和secret

**Comment by ugod3** [comment]
那我从RH-admin进入呢，在数据库内设置了账号密码，但是登不进去，这个是什么原因

**Comment by ugod3** [comment]
搭载在本地上，能满足这个项目什么功能呢

**Comment by LiuXIn011** [comment]
如果配置齐全是都可以满足的

**Comment by ugod3** [comment]
我现在不清楚哪一步落下了。。。按照文档上需要的服务和config.default.js的配置都搭载上了

**Comment by LiuXIn011** [comment]
错误信息提供一下

**Comment by ugod3** [comment]
![图片](https://github.com/LiuXIn011/rightHouse/assets/53908829/42ba8345-7a7e-4952-97e2-78196aea251c)
![图片](https://github.com/LiuXIn011/rightHouse/assets/53908829/8eb54497-caef-466b-b168-9b4fbf7a408a)

**Comment by LiuXIn011** [comment]
接口请求地址不对吧

**Comment by LiuXIn011** [comment]
![image](https://github.com/LiuXIn011/rightHouse/assets/48080203/6782f428-c409-463c-9fc2-fea5a16234a0)

**Comment by ugod3** [comment]
![图片](https://github.com/LiuXIn011/rightHouse/assets/53908829/6bf99902-46e5-4698-875a-0286df076e54)
这是要先访问到nginx服务端吗，nginx的地址是localhost:80,我没理解清楚，因为还没把房东端上传上nginx，试了下localhost:8080也不能直接连接到房东端

**Comment by LiuXIn011** [comment]
http://localhost:80
而且80端口是默认的，不需要指定
但是你要确定你的服务端端口，没有修改配置的情况下应该是7001

**Comment by ugod3** [comment]
![图片](https://github.com/LiuXIn011/rightHouse/assets/53908829/417f146d-8728-441e-b65e-f310b4c8000d)
# 接口访问地址配置
VITE_BASE_URL="7001" 

修改后是这样的

**Comment by LiuXIn011** [comment]
VITE_BASE_URL是你的服务端访问地址：
http://localhost + 你配置的服务端访问端口号

**Comment by ugod3** [comment]
![图片](https://github.com/LiuXIn011/rightHouse/assets/53908829/860a3e9c-458f-4fe2-a431-2432b5d76e00)
VITE_BASE_URL="http://localhost:7001"

**Comment by LiuXIn011** [comment]
看一下你服务端配置，config.default.js

**Comment by ugod3** [comment]
![图片](https://github.com/LiuXIn011/rightHouse/assets/53908829/411a7f8b-4254-4eb2-9beb-13d651fdb042)
![图片](https://github.com/LiuXIn011/rightHouse/assets/53908829/7c5cd601-8c0b-42da-a084-53d367811bbd)
![图片](https://github.com/LiuXIn011/rightHouse/assets/53908829/82df3c1c-1566-4044-ac48-e0ebd144b3ea)
![图片](https://github.com/LiuXIn011/rightHouse/assets/53908829/3fbe5e37-5b5e-4c22-9848-e07f97e5c4f5)

**Comment by LiuXIn011** [comment]
![image](https://github.com/LiuXIn011/rightHouse/assets/48080203/027dbc95-4d3c-451b-be8a-02e3b8865e8c)
你把默认端口修改为80了，那么你的VITE_BASE_URL应该是：
http://localhost

**Comment by ugod3** [comment]
.env内VITE_BASE_URL改成http://localhost吗，
![图片](https://github.com/LiuXIn011/rightHouse/assets/53908829/d835f3df-549e-4cbf-815b-36bd1cacb9ad)
改完之后是这样的

**Comment by ugod3** [comment]
我改回7001了

**Comment by LiuXIn011** [comment]
VITE_BASE_URL端口也改一下

**Comment by ugod3** [comment]
![图片](https://github.com/LiuXIn011/rightHouse/assets/53908829/e38add76-e78b-42cf-abd0-9bbecf183752)

**Comment by ugod3** [comment]
![图片](https://github.com/LiuXIn011/rightHouse/assets/53908829/4b2eb3b0-121b-47a7-bd19-f383b50eec6d)
房东端和租客端需要进入一定要企业微信的登录吗

**Comment by LiuXIn011** [comment]
没有企业认证的小程序不允许获取用户信息，所以无法登录

**Comment by ugod3** [comment]
这两个客户端可以改成和RH-adimin一样登录吗

**Comment by LiuXIn011** [comment]
你可以尝试一下

**Comment by ugod3** [comment]
我感觉有点困难......可以有偿请你帮忙修改吗

**Comment by LiuXIn011** [comment]
你不会是拿去做毕设吧

**Comment by ugod3** [comment]
我早毕业了，但是在找项目学习，小程序我还没学

**Comment by LiuXIn011** [comment]
我建议你自己动手尝试一下，开源软件的魅力就在于此。

**Comment by ugod3** [comment]
刚学编程，实在做不出来...同类型的还没找到类似的开源，想从小程序和移动端网页两种不同的方式学习一下，如果你会修改成移动端的方式对会很有帮助....

**Comment by ugod3** [comment]
单单一个接口我都没理解....只能来问你....例如租客端登录接口是微信登录，我想尝试的话会先去修改登录端口，但是我又在想会不会和其他有调用微信登录端口冲突
